//
//  JoinPresenter.swift
//  MoGong
//
//  Created by HL on 2022/06/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol JoinPresentationLogic
{
  func presentSomething(response: Join.Something.Response)
}

class JoinPresenter: JoinPresentationLogic
{
  weak var viewController: JoinDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Join.Something.Response)
  {
    let viewModel = Join.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
