//
//  BoardInteractor.swift
//  MoGong
//
//  Created by HL on 2022/06/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BoardBusinessLogic
{
  func doSomething(request: Board.Something.Request)
}

protocol BoardDataStore
{
  //var name: String { get set }
}

class BoardInteractor: BoardBusinessLogic, BoardDataStore
{
  var presenter: BoardPresentationLogic?
  var worker: BoardWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Board.Something.Request)
  {
    worker = BoardWorker()
    worker?.doSomeWork()
    
    let response = Board.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
