//
//  BoardPresenter.swift
//  MoGong
//
//  Created by HL on 2022/06/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BoardPresentationLogic
{
  func presentSomething(response: Board.Something.Response)
}

class BoardPresenter: BoardPresentationLogic
{
  weak var viewController: BoardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Board.Something.Response)
  {
    let viewModel = Board.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
