//
//  MainViewController.swift
//  MoGong
//
//  Created by HL on 2022/06/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol MainDisplayLogic: class
{
  func displaySomething(viewModel: Main.Something.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic
{
  var interactor: MainBusinessLogic?
  var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
  
  let headerView = UIView()
  let logoView = UIView()
  let settingView = UIView()
  let searchView = UIView()
  let scrollView: UICollectionView = {
    let flowLayout = UICollectionViewFlowLayout()
    flowLayout.scrollDirection = .horizontal
    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: flowLayout)
    return collectionView
  }()
  let spaceTableView = UITableView()
  let clubTableView = UITableView()
  let talkTableView = UITableView()
  
  final let scrollViewCellID = "ScrollViewCell"
  final let tableViewCellID = "TableViewCell"

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = MainInteractor()
    let presenter = MainPresenter()
    let router = MainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    self.setupHeaderView()
    self.setupScrollView()
    self.setupSpaceTableView()
    self.setupClubTableView()
    self.setupTalkTableView()
    
    doSomething()
  }
  
  private func setupHeaderView() {
    self.headerView.backgroundColor = .red
    self.view.addSubview(headerView)
    headerView.snp.makeConstraints { make in
      make.top.left.right.equalTo(self.view.safeAreaLayoutGuide)
      make.height.equalTo(100)
    }
    
    // 로고
    self.logoView.backgroundColor = .blue
    self.headerView.addSubview(logoView)
    self.logoView.snp.makeConstraints { make in
      make.width.height.equalTo(50)
      make.centerY.equalToSuperview()
      make.left.equalToSuperview().offset(20)
    }
    
    // 설정
    self.settingView.backgroundColor = .blue
    self.headerView.addSubview(self.settingView)
    self.settingView.snp.makeConstraints { make in
      make.width.height.equalTo(50)
      make.centerY.equalToSuperview()
      make.right.equalToSuperview().offset(-20)
    }
    
    // 검색
    self.searchView.backgroundColor = .blue
    self.headerView.addSubview(self.searchView)
    self.searchView.snp.makeConstraints { make in
      make.width.height.equalTo(50)
      make.centerY.equalToSuperview()
      make.right.equalTo(self.settingView.snp.left).offset(-20)
    }
  }
  
  private func setupScrollView() {
    self.scrollView.delegate = self
    self.scrollView.dataSource = self
    self.scrollView.backgroundColor = .green
    self.scrollView.register(ScrollViewCell.self, forCellWithReuseIdentifier: scrollViewCellID)
    self.view.addSubview(self.scrollView)
    self.scrollView.snp.makeConstraints { make in
      make.top.equalTo(self.headerView.snp.bottom).offset(20)
      make.left.right.equalTo(self.view.safeAreaLayoutGuide)
      make.height.equalTo(150)
    }
  }
  
  private func setupSpaceTableView() {
    self.spaceTableView.delegate = self
    self.spaceTableView.dataSource = self
    self.spaceTableView.backgroundColor = .brown
    self.spaceTableView.register(TableViewCell.self, forCellReuseIdentifier: tableViewCellID)
    self.view.addSubview(self.spaceTableView)
    self.spaceTableView.snp.makeConstraints { make in
      make.top.equalTo(self.scrollView.snp.bottom).offset(10)
      make.left.right.equalTo(self.view.safeAreaLayoutGuide)
      make.height.equalTo(150)
    }
  }
  
  private func setupClubTableView() {
    self.clubTableView.delegate = self
    self.clubTableView.dataSource = self
    self.clubTableView.backgroundColor = .cyan
    self.clubTableView.register(TableViewCell.self, forCellReuseIdentifier: tableViewCellID)
    self.view.addSubview(self.clubTableView)
    self.clubTableView.snp.makeConstraints { make in
      make.top.equalTo(self.spaceTableView.snp.bottom).offset(10)
      make.left.right.equalTo(self.view.safeAreaLayoutGuide)
      make.height.equalTo(150)
    }
  }
  
  private func setupTalkTableView() {
    self.talkTableView.delegate = self
    self.talkTableView.dataSource = self
    self.talkTableView.backgroundColor = .darkGray
    self.talkTableView.register(TableViewCell.self, forCellReuseIdentifier: tableViewCellID)
    self.view.addSubview(self.talkTableView)
    self.talkTableView.snp.makeConstraints { make in
      make.top.equalTo(self.clubTableView.snp.bottom).offset(10)
      make.left.right.equalTo(self.view.safeAreaLayoutGuide)
      make.height.equalTo(150)
    }
  }

  // MARK: Do something
  
  func doSomething()
  {
    let request = Main.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Main.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension MainViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
  func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    return 5
  }
  
  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    let cell = self.scrollView.dequeueReusableCell(withReuseIdentifier: scrollViewCellID, for: indexPath)
    cell.backgroundColor = .gray
    return cell
  }
  
  func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
    return CGSize(width: 120, height: 120)
  }
}

extension MainViewController: UITableViewDelegate, UITableViewDataSource {
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return 5
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = self.spaceTableView.dequeueReusableCell(withIdentifier: tableViewCellID, for: indexPath)
    cell.backgroundColor = .clear
    return cell
  }
}
