//
//  MainRouter.swift
//  MoGong
//
//  Created by HL on 2022/06/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
	func routeToJoin() {
		guard let vc = self.viewController?.storyboard?.instantiateViewController(withIdentifier: "Join") else { return }
		vc.modalPresentationStyle = .fullScreen
		self.viewController?.present(vc, animated: true)
	}
  
//  func routeToSomewhere(segue: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! JoinViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! JoinViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//  }

  // MARK: Navigation
  
//  func navigateToSomewhere(source: MainViewController, destination: JoinViewController)
//  {
//    source.show(destination, sender: nil)
//  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: MainDataStore, destination: inout JoinDataStore)
//  {
////    destination.name = source.name
//  }
}
